# This file was generated by GoReleaser. DO NOT EDIT.
cask "kss" do
  name "kss"
  desc "kss - Enhanced Kubernetes Pod Inspection"
  homepage "https://github.com/chmouel/kss"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kss"

  on_macos do
    url "https://github.com/chmouel/kss/releases/download/v#{version}/kss_Darwin_all.tar.gz"
    sha256 "efad07bd178225f76bf940212c8d58eb99d1e5cca61cbd54b90794d4db3e6cc1"
  end

  on_linux do
    on_intel do
      url "https://github.com/chmouel/kss/releases/download/v#{version}/kss_Linux_x86_64.tar.gz"
      sha256 "1d9905c5f22a669dcad6aa9c8d1329dc380d0d2abae416e63d25b741bf4ea553"
    end
    on_arm do
      url "https://github.com/chmouel/kss/releases/download/v#{version}/kss_Linux_arm64.tar.gz"
      sha256 "5ff0a18dcb56cf4f340c602a8141c816c7566e94bc7c9814a7a12bb217e3aa7c"
    end
  end

  # No zap stanza required
end
