# This file was generated by GoReleaser. DO NOT EDIT.
cask "kss" do
  name "kss"
  desc "kss - Enhanced Kubernetes Pod Inspection"
  homepage "https://github.com/chmouel/kss"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kss"

  on_macos do
    url "https://github.com/chmouel/kss/releases/download/v#{version}/kss_Darwin_all.tar.gz"
    sha256 "9944624d0ab7ea73c12a48ec41938b40d6bb684da604703c3313168159a1c99c"
  end

  on_linux do
    on_intel do
      url "https://github.com/chmouel/kss/releases/download/v#{version}/kss_Linux_x86_64.tar.gz"
      sha256 "45c96e43a8241a754aa73c922cc6796cdfd4d4d83abac231aa404dcbb5359c5e"
    end
    on_arm do
      url "https://github.com/chmouel/kss/releases/download/v#{version}/kss_Linux_arm64.tar.gz"
      sha256 "743e6aa2550197ba86266b247952a0488eaf6b9b17bb13a262670b15549fad45"
    end
  end

  # No zap stanza required
end
