# This file was generated by GoReleaser. DO NOT EDIT.
cask "tkss" do
  name "tkss"
  desc "tkss - Enhanced Tekton PipelineRun Inspection"
  homepage "https://github.com/chmouel/kss"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tkss"

  on_macos do
    url "https://github.com/chmouel/kss/releases/download/v#{version}/kss_Darwin_all.tar.gz"
    sha256 "458c210d59bb825bd59ba0a94b5671b86d3489109c5d743d3c69968649ae89f7"
  end

  on_linux do
    on_intel do
      url "https://github.com/chmouel/kss/releases/download/v#{version}/kss_Linux_x86_64.tar.gz"
      sha256 "a961f12f0ed18eea269a382089f61bffba83dfcf50ca30f2f361345253d9e80e"
    end
    on_arm do
      url "https://github.com/chmouel/kss/releases/download/v#{version}/kss_Linux_arm64.tar.gz"
      sha256 "e9c574ab54a598e1d5fd8e400865ad7d2a48926b7a040efe5a737feb1d0d3873"
    end
  end

  # No zap stanza required
end
